apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: student-app
        image: aqsaafzal99/student-app:v1
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "db-service"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "root"
        - name: DB_NAME
          value: "studentdb"